name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Bash
        run: sudo apt-get install -y bash

        
      - name: Rendre le script exécutable
        run: chmod +x compare_symlinks.sh

      - name: Créer les fichiers de test
        run: |
          echo "/tmp/link1 ➜ /tmp/target1" > file1.txt
          echo "/tmp/link1 ➜ /tmp/target1" > file2.txt

      - name: Exécuter le script
        run: ./compare_symlinks.sh file1.txt file2.txt

      - name: Check for errors
        run: |
          if [ $? -ne 0 ]; then
            echo "Script failed"
            exit 1
          fi